CREATE DATABASE IF NOT EXISTS tscrapper;
USE tscrapper;


DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    url VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    id VARCHAR(100) NOT NULL UNIQUE,
    flags INT DEFAULT 0,
)ENGINE=InnoDB;

CREATE TABLE posts (
    url VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(100) NOT NULL UNIQUE,
    comments INT DEFAULT 0;
    ups INT DEFAULT 0;
    FOREIGN KEY (author) REFERENCES users(username) ON DELETE CASCADE

)ENGINE=InnoDB;

CREATE TABLE comments (
    post_id VARCHAR(100) NOT NULL UNIQUE,
    parent_id VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(100) NOT NULL UNIQUE,
    body VARCHAR(255) NOT NULL UNIQUE,
    url VARCHAR(255) NOT NULL UNIQUE,
    ups INT DEFAULT 0;
    FOREIGN KEY (post_id) REFERENCES post(username) ON DELETE CASCADE
    FOREIGN KEY (author) REFERENCES user(username) ON DELETE CASCADE
)ENGINE=InnoDB;